#!/bin/bash

source ./env/env.sh $ENV

if [ -z $DISPLAY ]
then
  echo "${X11_ERROR}"
  exit 1
fi

function create_dir() {
  if [ ! -d "${1}" ]; then
    mkdir ${1}
    sudo chown ${USER}:${USER} ${1}
  fi
}

function create_dirs() {
  create_dir ~/.Idea
  create_dir ~/.Idea.java
  create_dir ~/.Idea.maven
  create_dir ~/.Idea.gradle
}

function pull_latest() {
  docker pull ${INTELLIJ}
}

function run() {
  docker run --rm \
             --detach \
             --env DISPLAY=${DISPLAY} \
             --volume /tmp/.X11-unix:/tmp/.X11-unix \
             --volume ~/.Idea:/home/developer/.Idea \
             --volume ~/.Idea.java:/home/developer/.java \
             --volume ~/.Idea.maven:/home/developer/.m2 \
             --volume ~/.Idea.gradle:/home/developer/.gradle \
             --volume $WORKSPACE:/home/developer/workspace \
             --name idea-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
             ${INTELLIJ}
}

create_dirs
pull_latest
run
